### ISSUE TITLE
Error on Meteor blaze Cannot set property 'Export' of undefined

### ISSUE THREAD

**Issue by Roshini369** [didanurwanda/DataTables-Export-Document#4]
Hi, I am getting an error while using your package, in meteor blaze 1.10 with datatables

The error says Cannot set property 'Export' of undefined

Is there any specific jquery version that i should be updating it. currently i am using jquery@3.4.1

**Comment by rotring01** [comment]
Uncaught TypeError: Cannot set properties of undefined (setting 'Export')
    at dataTables.export.js:250:27
    at dataTables.export.js:692:3
